### ISSUE TITLE
Plans for viz module

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#33]
_From @Garyfallidis  on June 1, 2018 21:28_  

Here some ideas for moving forward with the viz module. These are the notes after a call that I had with @MarcCote.

- [ ]  Currently the UI elements have on_xxx callbacks as attributes that can be set any time. We would like to have something similar for all the different actors too. For now you can connect an actor and it's callback using ShowManager.iren.add_callback. 

- [ ]  Timer_callbacks are currently added at the level of the ShowManager (see PR #1528). It maybe beneficial for simplicity to add a the generic add_callback function at the level of ShowManager rather iren.

- [ ]  Hovering event is currently not working very well. Needs some thinking.

- [x] Splitting of the viz module is scheduled for the next coming weeks and definitely before release 0.15.
@skoudoro and myself will lead the split. New project name is currently pending. Let us know if you have ideas.

- [ ] @karandeepSJ, @ranveeraggarwal and @naveenkumarmarri will have to update their PRs after recent merge of #1492 

- [ ] Simple image and track interface will be added by @garyfallidis

- [ ] The grid system will be added by @MarcCote.

- [ ] A 3D orbital menu needs to be refactored by @ranveeraggarwal 

- [ ] Shaders will be added by @dmreagan, @thechargedneutron and myself. Others more than welcome to contribute.

- [ ] The record events mechanism in tests needs to be reconsidered. It is currently difficult to replicate the test. Maybe we should be using our own timer_callbacks (see tests of #1528) . Will have to put some use cases down and see what we can get.

- [x] Support for old vtk versions (< vtk 8.1) should be removed. With the new PYPI installers for VTK packaging is much easier.  And the code can become simpler.

@MarcCote and all, update here if we some information is missing. 

_Copied from original issue: nipy/dipy#1544_

**Comment by arokem** [comment]
Related (I think?) Is there already a `pip install` for Python 3.7 for recent VTK?

**Comment by skoudoro** [comment]
yes @arokem, see [here](https://pypi.org/project/vtk/8.1.2/#files). they made a new release last week

**Comment by skoudoro** [comment]
_from @MarcCote on July 23, 2016 18:45_

# Dipy PR's

This document describes the list of Pull Requests that needs to be merge into Dipy's Master. Except stated otherwise the up-to-date code can be found in the branch https://github.com/Garyfallidis/dipy/tree/recobundles.

_This issue is mainly for @Garyfallidis and me to track down which PRs still need to be made._
## Small
### dipy/viz/colormap.py:distinguishable_colormap

Generates colors that are maximally perceptually distinct.
- [x] Code 
- [x] DOC
- [ ] TEST
- [x] Example
### dipy/viz/actor.py:slicer

We need to check what changed.
- [x] Code 
- [x] DOC
- [x] TEST
- [x] Example
### dipy/viz/actor.py:odf_slicer

I don't think this one is urgent?
- [x] Code 
- [x] DOC
- [x] TEST
- [x] Example
### dipy/viz/actor.py:text_overlay

Maybe we should wait for the Ranveer's 2D UI component.
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/actor.py:text_3d

I've started to make some tests for this one(see https://github.com/MarcCote/dipy/tree/TST_text3d).
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/actor.py:figure

TODO.
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py

This PR would include only the functions vtk_matrix_to_numpy, numpy_to_vtk_matrix, shallow_copy, get_bounding_box_sizes. It would also fixes typos and other small changes.
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py:vtk_matrix_to_numpy and dipy/viz/utils.py:numpy_to_vtk_matrix

TODO
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py:matplotlib_figure_to_numpy

TODO
- [ ] DOC
- [ ] TEST
- [ ] Example
## Medium
### dipy/viz/actor.py:Container

This also includes dipy/viz/actor.py:grid, dipy/viz/utils.py:get_grid_cells_position and the whole file dipy/viz/layout.py
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py:auto_orient and dipy/viz/utils.py:auto_camera

We need to better define their behavor and make some tests. 
- [ ] DOC
- [ ] TEST
- [ ] Example
## Big
### dipy/viz/timeline.py

TODO
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/segment/clustering.py:QuickBundlesX

TODO
- [x] Code
- [ ] DOC
- [x] TEST
- [ ] Example
### dipy/segment/clustering.py:QuickBundlesOnline

We should check if we couldn't integrate the Online behavior directly to QuickBundles and QuickBundlesX.
- [ ] Code 
- [ ] DOC
- [ ] TEST
- [ ] Example

Copied from original issue: _nipy/dipy#1099_
